apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solution
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: $1
    kubernetes.io/ingress.global-static-ip-name: creators-contest-2022-ip
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /solutions/team-{{.Values.team}}(/.*)?
            pathType: ImplementationSpecific
            backend:
              service:
                name: solution
                port:
                  number: 8080
      host: {{.Values.ingress.host}}